spring:
  datasource:
    url: "jdbc:postgresql://172.80.2.1:5432/leader_framework?sslmode=disable"
    username: mailagent_user
    password: mailagent_password

mail:
  protocol: maildev
  poll-interval-seconds: 30

maildev:
  api-url: http://172.80.2.1:18080

memory:
  service:
    enabled: false

mock:
  agent: true
