spring.datasource.url=jdbc:postgresql://172.80.2.1:5432/leader_framework?sslmode=disable
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=memory_user
spring.datasource.password=memory_password

spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=memory
spring.flyway.default-schema=memory
