spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/techlead
    username: techlead
    password: ${POSTGRES_MEMORY_PASSWORD}
    hikari:
      maximum-pool-size: 5
  flyway:
    locations: classpath:db/migration
