spring.datasource.url=jdbc:postgresql://localhost:5432/techlead
spring.datasource.username=techlead
spring.datasource.password=techlead
spring.datasource.hikari.maximum-pool-size=5
spring.flyway.locations=classpath:db/migration
